<a href="https://colab.research.google.com/github/Aseem2004/Demo/blob/main/Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
a=pd.read_csv("https://github.com/YBIFoundation/Dataset/raw/main/Titanic.csv")
print(a)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton
1          1         1                   Allison, Master. Hudson Trevor
2          1         0                     Allison, Miss. Helen Loraine
3          1         0             Allison, Mr. Hudson Joshua Creighton
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1304       3         0                             Zabour, Miss. Hileni
1305       3         0                            Zabour, Miss. Thamine
1306       3         0                        Zakarian, Mr. Mapriededer
1307       3         0                              Zakarian, Mr. Ortin
1308       3         0                               Zimmerman, Mr. Leo

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00      0      0   24160  211.3375       B5        S    2
1       male   0.92      1      2  113781  151.5500  C22 C26        S   11
2     female   2.00      1      2  113781  151.5500  C22 C26        S  NaN
3       male  30.00      1      2  113781  151.5500  C22 C26        S  NaN
4     female  25.00      1      2  113781  151.5500  C22 C26        S  NaN
...      ...    ...    ...    ...     ...       ...      ...      ...  ...
1304  female  14.50      1      0    2665   14.4542      NaN        C  NaN
1305  female    NaN      1      0    2665   14.4542      NaN        C  NaN
1306    male  26.50      0      0    2656    7.2250      NaN        C  NaN
1307    male  27.00      0      0    2670    7.2250      NaN        C  NaN
1308    male  29.00      0      0  315082    7.8750      NaN        S  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1304  328.0                              NaN
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN

[1309 rows x 14 columns]

In [7]:
a.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [5]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

In [6]:
a.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000